name: Deploy Pages
on:
  push:
    branches: [gh-pages] # Как только прилетает отчет, обновляем сайт
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages # <-- Параметр скачивания ветки должен быть ЗДЕСЬ

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Теперь он возьмет файлы из скачанной ветки gh-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
